//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.01 at 09:58:22 AM CEST 
//


package org.kasource.jmx.core.model.dashboard;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for colorSchemaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="colorSchemaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="heat_map"/>
 *     &lt;enumeration value="green_to_red"/>
 *     &lt;enumeration value="bolivia"/>
 *     &lt;enumeration value="mexico"/>
 *     &lt;enumeration value="gray"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "colorSchemaType")
@XmlEnum
public enum ColorSchemaType {

    @XmlEnumValue("heat_map")
    HEAT_MAP("heat_map"),
    @XmlEnumValue("green_to_red")
    GREEN_TO_RED("green_to_red"),
    @XmlEnumValue("bolivia")
    BOLIVIA("bolivia"),
    @XmlEnumValue("mexico")
    MEXICO("mexico"),
    @XmlEnumValue("gray")
    GRAY("gray");
    private final String value;

    ColorSchemaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ColorSchemaType fromValue(String v) {
        for (ColorSchemaType c: ColorSchemaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
