//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.01 at 09:58:22 AM CEST 
//


package org.kasource.jmx.core.model.dashboard;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.kasource.jmx.core.dashboard.AttributeValuePopulator;
import org.kasource.jmx.core.dashboard.DashboardWidget;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://kasource.org/schema/ka-jmx}heatRow" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="showLegend" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="legendLayout" type="{http://kasource.org/schema/ka-jmx}layoutType" default="vertical" />
 *       &lt;attribute name="colorSchema" use="required" type="{http://kasource.org/schema/ka-jmx}colorSchemaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "heatRow"
})
@XmlRootElement(name = "heatMap")
public class HeatMap implements DashboardWidget {

    @XmlElement(required = true)
    protected List<HeatRow> heatRow;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    protected boolean showLegend = true;
    @XmlAttribute
    protected LayoutType legendLayout = LayoutType.VERTICAL;
    @XmlAttribute(required = true)
    protected ColorSchemaType colorSchema = ColorSchemaType.HEAT_MAP;

    /**
     * Gets the value of the heatRow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the heatRow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeatRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HeatRow }
     * 
     * 
     */
    public List<HeatRow> getHeatRow() {
        if (heatRow == null) {
            heatRow = new ArrayList<HeatRow>();
        }
        return this.heatRow;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the showLegend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowLegend() {     
         return showLegend;      
    }

    /**
     * Sets the value of the showLegend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowLegend(boolean value) {
        this.showLegend = value;
    }

    /**
     * Gets the value of the legendLayout property.
     * 
     * @return
     *     possible object is
     *     {@link LayoutType }
     *     
     */
    public LayoutType getLegendLayout() {
        if (legendLayout == null) {
            return LayoutType.VERTICAL;
        } else {
            return legendLayout;
        }
    }

    /**
     * Sets the value of the legendLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayoutType }
     *     
     */
    public void setLegendLayout(LayoutType value) {
        this.legendLayout = value;
    }

    /**
     * Gets the value of the colorSchema property.
     * 
     * @return
     *     possible object is
     *     {@link ColorSchemaType }
     *     
     */
    public ColorSchemaType getColorSchema() {
        return colorSchema;
    }

    /**
     * Sets the value of the colorSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorSchemaType }
     *     
     */
    public void setColorSchema(ColorSchemaType value) {
        this.colorSchema = value;
    }

    @Override
    public String getType() {
        return "heatMap";
    }

    /**
     * @param heatRow the heatRow to set
     */
    public void setHeatRow(List<HeatRow> heatRow) {
        this.heatRow = heatRow;
    }

    @Override
    public void populateValues(AttributeValuePopulator populator) {
        for(HeatRow row : heatRow) {
            for(HeatCell cell : row.getHeatCell()) {
                populator.populateValue(cell.getData());
               
            }
        }
    }

}
