//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.24 at 05:35:32 PM CEST 
//


package org.kasource.jmx.core.model.dashboard;







import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kasource.schema.ka_jmx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kasource.schema.ka_jmx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttributeValue }
     * 
     */
    public AttributeValue createAttributeValue() {
        return new AttributeValue();
    }
    
    /**
     * Create an instance of {@link LedPanel }
     * 
     */
    public LedPanel createLedPanel() {
        return new LedPanel();
    }

    /**
     * Create an instance of {@link TextGroup }
     * 
     */
    public TextGroup createTextGroup() {
        return new TextGroup();
    }

    /**
     * Create an instance of {@link Panel }
     * 
     */
    public Panel createPanel() {
        return new Panel();
    }

    /**
     * Create an instance of {@link Pie }
     * 
     */
    public Pie createPie() {
        return new Pie();
    }
    
    /**
     * Create an instance of {@link Graph }
     * 
     */
    public Graph createGraph() {
        return new Graph();
    }
    
    /**
     * Create an instance of {@link TrafficLight }
     * 
     */
    public TrafficLight createTrafficLight() {
        return new TrafficLight();
    }


    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

  

    /**
     * Create an instance of {@link Gauge }
     * 
     */
    public Gauge createGauge() {
        return new Gauge();
    }

    /**
     * Create an instance of {@link Dashboard }
     * 
     */
    public Dashboard createDashboard() {
        return new Dashboard();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }
    
    /**
     * Create an instance of {@link HeatRow }
     * 
     */
    public HeatRow createHeatRow() {
        return new HeatRow();
    }

    
    /**
     * Create an instance of {@link HeatCell }
     * 
     */
    public HeatCell createHeatCell() {
        return new HeatCell();
    }

  
    /**
     * Create an instance of {@link HeatMap }
     * 
     */
    public HeatMap createHeatMap() {
        return new HeatMap();
    }

}
