//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.24 at 05:35:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kasource.org/schema/ka-jmx", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kasource.jmx.core.model.dashboard;
