//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.26 at 02:01:21 PM CEST 
//


package org.kasource.jmx.core.model.dashboard;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.kasource.jmx.core.dashboard.AttributeValuePopulator;
import org.kasource.jmx.core.dashboard.DashboardWidget;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="red" type="{http://kasource.org/schema/ka-jmx}attributeValue"/>
 *         &lt;element name="yellow" type="{http://kasource.org/schema/ka-jmx}attributeValue"/>
 *         &lt;element name="green" type="{http://kasource.org/schema/ka-jmx}attributeValue"/>
 *         &lt;element name="value" type="{http://kasource.org/schema/ka-jmx}attributeValue"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="suffix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="state" type="{http://kasource.org/schema/ka-jmx}trafficLightState" />
 *       &lt;attribute name="ascending" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "red",
    "yellow",
    "green",
    "value"
})
@XmlRootElement(name = "trafficLight")
public class TrafficLight implements DashboardWidget {

    @XmlElement(required = true)
    protected AttributeValue red;
    @XmlElement(required = true)
    protected AttributeValue yellow;
    @XmlElement(required = true)
    protected AttributeValue green;
    @XmlElement(required = true)
    protected AttributeValue value;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    protected String suffix;
    @XmlAttribute
    protected String prefix;
    @XmlAttribute
    protected String title;
    @XmlAttribute
    protected TrafficLightState state;
    @XmlAttribute
    protected boolean ascending = true;
    @XmlAttribute(required = true)
    protected AttributeType attributeType = AttributeType.NUMERIC;
    
    /**
     * Gets the value of the red property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValue }
     *     
     */
    public AttributeValue getRed() {
        return red;
    }

    /**
     * Sets the value of the red property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeValue }
     *     
     */
    public void setRed(AttributeValue value) {
        this.red = value;
    }

    /**
     * Gets the value of the yellow property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValue }
     *     
     */
    public AttributeValue getYellow() {
        return yellow;
    }

    /**
     * Sets the value of the yellow property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeValue }
     *     
     */
    public void setYellow(AttributeValue value) {
        this.yellow = value;
    }

    /**
     * Gets the value of the green property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValue }
     *     
     */
    public AttributeValue getGreen() {
        return green;
    }

    /**
     * Sets the value of the green property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeValue }
     *     
     */
    public void setGreen(AttributeValue value) {
        this.green = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValue }
     *     
     */
    public AttributeValue getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeValue }
     *     
     */
    public void setValue(AttributeValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link TrafficLightState }
     *     
     */
    public TrafficLightState getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrafficLightState }
     *     
     */
    public void setState(TrafficLightState value) {
        this.state = value;
    }

    /**
     * Gets the value of the ascending property.
     * 
     * @return
     *     possible object is
     *     {@link boolean }
     *     
     */
    public boolean isAscending() {
        return ascending;
    }

    /**
     * Sets the value of the ascending property.
     * 
     * @param value
     *     allowed object is
     *     {@link boolean }
     *     
     */
    public void setAscending(boolean value) {
        this.ascending = value;
    }

    @Override
    public String getType() {
        return "trafficLight";
    }

    /**
     * @return the attributeType
     */
    public AttributeType getAttributeType() {
        return attributeType;
    }

    /**
     * @param attributeType the attributeType to set
     */
    public void setAttributeType(AttributeType attributeType) {
        this.attributeType = attributeType;
    }

    @Override
    public void populateValues(AttributeValuePopulator populator) {
        populator.populateValue(red);
        populator.populateValue(yellow);
        populator.populateValue(green);
        populator.populateValue(value);
        
    }

}
